DROP TABLE IF EXISTS Mpa, Genres, Likes, Users, Films, Friendship, Film_genre, Feed;

CREATE TABLE IF NOT EXISTS  Users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS Films(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    genre VARCHAR,
    mpa INTEGER,
    likes INTEGER
);

CREATE TABLE IF NOT EXISTS Friendship (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER  REFERENCES users(id),
    communication_status BIT DEFAULT(FALSE)
);

CREATE TABLE IF NOT EXISTS Likes(
    user_id INTEGER REFERENCES users(id),
    film_id INTEGER REFERENCES films(id),
    CONSTRAINT id PRIMARY KEY(user_id, film_id)
);

CREATE TABLE IF NOT EXISTS Genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS Mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS  Film_genre(
    film_id INTEGER REFERENCES Films(id),
    genre_id INTEGER REFERENCES Genres(id),
    CONSTRAINT ident PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Feed (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES Users(id),
    entity_id INTEGER,
    event_type VARCHAR,
    operation VARCHAR,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
